#! /bin/bash

# When upgrading dovecot-core durint stretch->buster the ssl conf file
# where added to UCF management from unmanaged. This resulted in an
# unusable dovecot, no dh-params.
# This script tries to makes sure we run the new package provided version

CFILE="/etc/dovecot/conf.d/10-ssl.conf"

echo "Check for faulty dovecot ssl config"

if [ -e "${CFILE}.ucf-dist" ]
then
	echo "Found stale ssl config file"
	if [ -e "${CFILE}" ]
	then
		echo "Saving original ssl config"
		mv "${CFILE}" "${CFILE}.kgp-update"
	fi
	echo "Update with new version"
	mv "${CFILE}.ucf-dist" "${CFILE}"

	systemctl reload dovecot.service
fi
