#! /bin/bash

# When upgrading dovecot-core durint stretch->buster the ssl conf file
# where added to UCF management from unmanaged. This resulted in an
# unusable dovecot, no dh-params.
# This script tries to makes sure we run the new package provided version

LOGNAME="${LOGNAME}: Dovecot migrate"
source /usr/share/kgp-bashlibrary/scripts/kgp-logging.sh

CFILE="/etc/dovecot/conf.d/10-ssl.conf"

log_debug "Check for faulty dovecot ssl config"

if [ -e "${CFILE}.ucf-dist" ]
then
	log_info "Found stale ssl config file"
	if [ -e "${CFILE}" ]
	then
		log_info "Saving original ssl config"
		mv "${CFILE}" "${CFILE}.kgp-update"
	fi
	log_info "Update with new version"
	mv "${CFILE}.ucf-dist" "${CFILE}"

	systemctl reload dovecot.service
fi
